name: Test an apworld
description: Setup a base archipelago installation and run tests for the given apworld
inputs:
  ap-version:
    description: The version of archipelago to use. This must either match a refspec in the archipelago repository or be 'latest' to match the latest stable release.
    required: true
  python-version:
    description: The python version to use
    required: true
  apworld-path:
    description: The path to the apworld folder or apworld itself
    required: true
  apworld-name:
    description: The name of the apworld. This should only be set if the folder storing your apworld in the repository isn't the same
    type: string
    default: ""
  checkout:
    description: Whether or not to run the checkout step. Can be useful to disable if you want to run tests on a dirty repo
    default: true
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@master
      if: ${{ inputs.checkout != 'false' }}

    - uses: Eijebong/ap-actions/setup-ap@main
      with:
        version: ${{ inputs.ap-version }}
        python-version: ${{ inputs.python-version }}

    - name: Determine apworld name
      shell: bash
      run: |
        if [[ "${APWORLD_NAME}" == "" ]]; then
          if [[ "${APWORLD_PATH}" == *.apworld ]]; then
            echo "APWORLD_NAME=$(basename "${APWORLD_PATH}" .apworld)" >> $GITHUB_ENV
          else
            echo "APWORLD_NAME=$(basename "${APWORLD_PATH}")" >> $GITHUB_ENV
          fi
        else
          echo "APWORLD_NAME=${APWORLD_NAME}" >> $GITHUB_ENV
        fi
      env:
        APWORLD_PATH: ${{ inputs.apworld-path }}
        APWORLD_NAME: ${{ inputs.apworld-name }}

    - name: Copy apworld in worlds
      shell: bash
      run: |
        if [[ "${APWORLD_PATH}" == *.apworld ]]; then
          unzip -q "${APWORLD_PATH}" -d archipelago/worlds/
        else
          mkdir -p archipelago/worlds/${APWORLD_NAME}
          rsync --exclude archipelago --exclude .git -ap ${APWORLD_PATH}/* archipelago/worlds/${APWORLD_NAME}
        fi

      env:
        APWORLD_PATH: ${{ inputs.apworld-path }}

    - name: Copy test runner
      shell: bash
      run: |
        cp ${GITHUB_ACTION_PATH}/run_tests.py archipelago/run_tests.py

    - name: Run tests
      shell: bash
      run: |
        cd archipelago && uv run python run_tests.py ${APWORLD_NAME}
