name: Setup archipelago
description: Setup a base archipelago installation
inputs:
  version:
    description: The version of archipelago to use. This must match a refspec in the archipelago repository
    required: true
  python-version:
    description: The python version to use
    required: true
outputs:
  path:
    description: The root of the archipelago installation
    value: archipelago
runs:
  using: composite
  steps:
    - name: Get AP Tag
    id: getAPtag
    run: |
    if [[ "${{inputs.version}}" == "latest" ]]; then
      echo "::set-output name=releasetag::$(curl -s https://api.github.com/repos/ArchipelagoMW/Archipelago/releases/latest | jq '.tag_name' | sed 's/\"//g')"
    fi
    if [[ "${{inputs.version}}" != "latest" ]]; then
      echo "::set-output name=releasetag::${{inputs.version}}"
    fi
    - name: Echo chosen releasetag
    run: echo "Chosen AP Release version to grab: ${{steps.getAPtag.outputs.releasetag}}"
    - name: Clone archipelago
      uses: actions/checkout@master
      id: clone
      with:
        repository: ArchipelagoMW/Archipelago
        ref: ${{inputs.version}}
        path: archipelago
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
        python-version: ${{inputs.python-version}}
        enable-cache: true
    - name: Install dependencies
      shell: bash
      run: |
        cd archipelago/
        uv venv
        uv pip install pip
        find -name requirements.txt | xargs -n1 uv pip install -r
        uv pip install setuptools
        uv run cythonize -a -i _speedups.pyx
        uv run python ModuleUpdate.py --yes
    - name: Create custom worlds folder
      shell: bash
      run: |
        mkdir -p archipelago/custom_worlds
