name: Test-AP-Setup
on:
  workflow_dispatch:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "~3.12.6"
        cache: pip
    - name: Fuzzer-Check-1-yml
      uses: SomeJakeGuy/ap-actions/setup-ap@SJG-APInputVersion
      with:
        version: 'latest'
        python-version: '3.12'
